# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotuser',
            name='localization',
            field=models.CharField(default='kosmos', max_length=27),
            preserve_default=False,
        ),
    ]
