# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27)),
                ('location', models.CharField(max_length=27)),
                ('type', models.IntegerField(choices=[(1, 'View'), (2, 'Food'), (3, 'Restaurant'), (4, 'Urban exploration'), (5, 'City attraction'), (6, 'Cafe'), (7, 'Experience/story'), (8, 'Wild sleeping'), (9, 'Activity'), (10, 'Party'), (11, 'Nature')])),
                ('was_there', models.BooleanField()),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Photo')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
