# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_point_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(upload_to='static/media', verbose_name='Photo'),
        ),
    ]
