# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_auto_20170711_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Photo'),
        ),
    ]
