# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_auto_20170712_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='location',
            field=models.CharField(max_length=243),
        ),
    ]
